# Generated by Django 2.0.5 on 2018-09-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_comment', '0002_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
