# Generated by Django 2.0.5 on 2018-09-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
