# Generated by Django 2.0.5 on 2018-08-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='信息板块标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='详细信息')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('image', models.ImageField(upload_to='photo')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': '信息模块列表',
                'db_table': 'about',
                'ordering': ['priority'],
            },
        ),
    ]
