# Generated by Django 2.0.5 on 2018-08-23 07:41

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180823_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
