# Generated by Django 2.0.5 on 2018-08-25 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180824_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专栏类别')),
                ('created_time', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modified_time', models.DateField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '专栏类别',
                'verbose_name_plural': '专栏分类列表',
                'db_table': 'column_category',
            },
        ),
        migrations.AlterField(
            model_name='column',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ColumnCategory', verbose_name='专栏列表'),
        ),
    ]
