# Generated by Django 2.0.5 on 2018-08-27 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180826_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='用户标语')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.CharField(max_length=300, verbose_name='链接地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('created_time', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('hide', '显示'), ('show', '影藏')], default='hide', max_length=10, verbose_name='显示状态')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接列表',
                'db_table': 'friend_links',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
