# Generated by Django 2.0.5 on 2018-08-27 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180827_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'ordering': ['created_time'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息设置'},
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='modified_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AlterModelTable(
            name='baseinfo',
            table='base_info',
        ),
    ]
