# Generated by Django 2.0.5 on 2018-08-31 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_visitcount_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='visit_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='最近访问时间'),
        ),
    ]
