# Generated by Django 2.0.5 on 2018-08-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '发表')], default='publish', max_length=1, verbose_name='文章状态'),
        ),
    ]
