# Generated by Django 2.0.5 on 2018-09-12 15:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
