# Generated by Django 2.0.5 on 2018-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180918_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '发表'), ('hide', '隐藏')], default='publish', max_length=10, verbose_name='文章状态'),
        ),
    ]
