# Generated by Django 2.0.5 on 2018-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180823_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='priority',
            field=models.PositiveIntegerField(default=10000, verbose_name='优先级'),
        ),
    ]
