# Generated by Django 2.0.5 on 2018-08-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180823_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='excerpt',
            new_name='digest',
        ),
    ]
