# Generated by Django 2.0.5 on 2018-08-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180825_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='博客专栏'),
        ),
        migrations.AlterField(
            model_name='columncategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='专栏类别'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='标签名'),
        ),
    ]
