# Generated by Django 2.0.5 on 2018-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180827_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslinks',
            name='status',
            field=models.CharField(choices=[('hide', '隐藏'), ('show', '显示')], default='hide', max_length=10, verbose_name='显示状态'),
        ),
    ]
