# Generated by Django 2.0.5 on 2018-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180827_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='small_website_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='网站小标题'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='website_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='网站名称'),
        ),
    ]
