# Generated by Django 2.0.5 on 2018-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_userip_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcount',
            name='page_name',
            field=models.CharField(default='home', max_length=30, verbose_name='访问页面'),
        ),
    ]
