# Generated by Django 2.0.5 on 2018-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_visitcount_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='访问次数'),
        ),
        migrations.AlterField(
            model_name='visitcount',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='网站访问总次数'),
        ),
    ]
