# Generated by Django 2.0.5 on 2018-09-14 17:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=320, verbose_name='留言'),
        ),
    ]
