# Generated by Django 2.0.5 on 2018-09-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180915_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=280, verbose_name='留言'),
        ),
    ]
