# Generated by Django 2.0.5 on 2018-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180912_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='标语'),
        ),
    ]
