# Generated by Django 2.0.5 on 2018-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '发表')], default='publish', max_length=10, verbose_name='文章状态'),
        ),
    ]
