# Generated by Django 2.0.5 on 2018-10-04 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hide', '隐藏'), ('public', '公开')], default='public', max_length=10, verbose_name='留言状态')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(max_length=280, verbose_name='留言')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言列表',
                'db_table': 'message',
                'ordering': ['-submit_date'],
            },
        ),
    ]
