# Generated by Django 2.0.5 on 2018-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('hide', '隐藏'), ('public', '公开')], default='public', max_length=10, verbose_name='留言状态'),
        ),
    ]
