# Generated by Django 2.0.5 on 2018-09-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_comment', '0004_auto_20180918_2210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favour',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favour',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favour',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favour',
        ),
    ]
